recruiting_service/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staff.urls')),
    path('', include('result_checking_module.urls'))
]

staff/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('sith_auth', views.sith_auth, name='sith_auth'),
    path('recruiter_auth', views.recruiter_auth, name='recruiter_auth'),
]

staff/models.py
from django.core.mail import EmailMessage, send_mail
from django.db import models
from django.template.loader import get_template
from django.utils import timezone
# Create your models here.
from recruiting_service import settings


class Planet(models.Model):
    name = models.CharField('Planet`s name', max_length=50)

    def __str__(self):
        return self.name


class Recruiter(models.Model):
    name = models.CharField('Recruiter`s name', max_length=50)
    birth_date = models.DateField('Birth date')
    email = models.EmailField('Email', unique=True)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)

    def get_age(self):
        today = timezone.now()
        return ((today.date() - self.birth_date) / 365.25).days

    def __str__(self):
        return self.email

    def send_notification(self, subject, template_name, context=None):
        from_email, to = settings.EMAIL_HOST_USER, self.email
        html_content = get_template(template_name=template_name).render(context)
        msg = EmailMessage(subject, html_content, from_email, [to])
        msg.content_subtype = 'html'
        msg.send()


class Clan(models.Model):
    name = models.CharField('Order`s name', max_length=50)
    planet = models.ForeignKey(Planet, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Sith(models.Model):
    name = models.CharField('Sith`s name', max_length=50)
    clan = models.ForeignKey(Clan, on_delete=models.CASCADE)

    def __str__(self):
        return '{0} #{1}'.format(self.name, self.id)

    def count_of_dark_hand(self):
        return len(DarkHand.objects.filter(sith=self))


class DarkHand(models.Model):
    sith = models.ForeignKey(Sith, on_delete=models.CASCADE)
    recruiter = models.OneToOneField(Recruiter, on_delete=models.CASCADE)

staff/forms.py
from django import forms
from staff.models import Recruiter, Sith


class RecruiterForm(forms.ModelForm):

    class Meta:
        model = Recruiter
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(RecruiterForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self.fields['birth_date'].widget.attrs['placeholder'] = 'dd/mm/yyyy'


class SithForm(forms.Form):
    siths_select = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-control', 'required': True}))

    def __init__(self, *args, **kwargs):
        super(SithForm, self).__init__(*args, **kwargs)
        sith_objs = [[obj.id, obj.name] for obj in Sith.objects.all()]
        self.fields['siths_select'].choices = sith_objs

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    <a href="{% url 'index' %}" class="btn btn-primary">В начало</a>
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
<div class="row">
    <a class="col-md-6 text-center vh-100" href="{% url 'sith_auth' %}">
        <div class="align-middle mt-4">
            Для ситхов
        </div>
    </a>
    <a class="col-md-6 text-center vh-100" href="{% url 'recruiter_auth' %}">
        <div class="align-middle mt-4">
            Для рекрутов
        </div>
    </a>
</div>
{% endblock %}

templates/recruiter_answers.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}
    Ответы на тест рекрута
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <div class="col-md-6 mt-2 ml-auto mr-auto">
            <ul class="list-group">
                {% for answer in answers %}
                    <li class="list-group-item ">
                        <div class="float-left">
                            <h5>{{ answer.question.text }}</h5>
                            <h6>{{ answer.answer }}</h6>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            <div class="mt-2">
                <a  href="{% url 'recruiters_for_sith' %}"
                        class="btn btn-default float-left">Отмена</a>
                <button type="submit" class="btn btn-primary text-white float-right">Принять рукой тьмы</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/recruiter_auth.html
{% extends 'base.html' %}

{% block title %}
    Регистрация рекрутера
{% endblock %}

{% block content %}
<div class="col-md-6 ml-auto mr-auto mt-4">
    <h2>Регистрация</h2>
    <div class="row">
        <div class="col-md-6">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Имя</label>
                    {{ recruiter_registration_form.name }}
                </div>
                <div class="form-group">
                    <label for="id_birth_date">Дата рождения</label>
                    {{ recruiter_registration_form.birth_date }}
                </div>
                <div class="form-group">
                    <label for="id_email">Email</label>
                    {{ recruiter_registration_form.email }}
                </div>
                <div class="form-group">
                    <label for="id_planet">Планета</label>
                    {{ recruiter_registration_form.planet }}
                </div>
                <button type="submit" class="btn btn-primary">Далее</button>

            </form>
        </div>
        <div class="col-md-6">
            {{ recruiter_registration_form.errors }}
        </div>
    </div>

</div>
{% endblock %}

templates/recruiters_for_sith.html
{% extends 'base.html' %}

{% block title %}
    Рекруты и их ответы
{% endblock %}

{% block content %}
    <div class="row ml-auto mr-auto mt-2">
        <div class="col-md-4 ">
            Ситх: <strong>{{ sith.name }}</strong>
            <ul class="list-group">
                {% for dark_hand in dark_hands %}
                    <li class="list-group-item ">
                        <h5>{{ dark_hand.recruiter.name }}</h5>
                        <h6>{{ recruiter.recruiter.email }}</h6>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-6 ">
            {% if recruiters %}
                <ul class="list-group">
                    {% for recruiter in recruiters %}
                        <li class="list-group-item ">
                            <div class="float-left">
                                <h5>{{ recruiter.name }}</h5>
                                <h6>{{ recruiter.email }}</h6>
                            </div>
                            <a  href="{% url 'user_answers' recruiter.id %}"
                                class="btn btn-primary text-white float-right">Посмотреть ответы</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Нет доступных рекрутов</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/sith_auth.html
{% extends 'base.html' %}

{% block title %}
    Вход ситхов
{% endblock %}

{% block content %}
    <div class="col-md-6 mt-4 m-auto text-center">
        <form method="POST">
            {% csrf_token %}
            <label for="id_siths_select"></label>
            {{ choice_sith_form.siths_select }}
            <button type="submit" class="btn btn-primary mt-2">Далее</button>
        </form>
    </div>
{% endblock %}

templates/test_for_recruiter.html
{% extends 'base.html' %}
{% load filters %}

{% block title %}
    Тест
{% endblock %}

{% block content %}
    <form method="POST" class="col-md-7 m-auto text-center">
        {% csrf_token %}
        <h2 class="text-center">{{ test_title }}</h2>
        <ul class="list-group ">
            {% for question in questions %}
                <li class="list-group-item">
                    <h5>{{ question|get:'title' }}</h5>
                    <div class="row">
                        <p class="p-2">{{ question|get:'text' }}</p>
                        <div class="p-2">
                            {{ question|get:'answer_form' }}
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
        <button type="submit" class="btn btn-primary mt-2 ">Далее</button>
    </form>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}

{% block title %}
    Спасибо
{% endblock %}

{% block content %}
    <div class="col-md-6 m-auto text-center">
        <p>Спасибо за участие</p>
        <a href="{% url 'index' %}">Вернуться на главную</a>
    </div>
{% endblock %}